services:
  web:
    container_name: balunga_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "${VIRTUAL_PORT}"
    volumes:
      - .:/app
    environment:
      - DEBUG_MODE=False
      - "VIRTUAL_PORT=${VIRTUAL_PORT}"
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"
    command: java -jar /app/target/balunga.jar
    deploy:
      resources:
        limits:
          cpus: "${LIMIT_CPU}"
          memory: "${LIMIT_MEM}"
    networks:
      - default

networks:
  default:
    name: "${NETWORK}"

